---
# file     : roles/system/tasks/main.yml
# purpose  : provision non common settings for system{1..2}
#
# author   : harald van der laan
# date     : 2017/03/15
# version  : v1.0.0
#
# changelog:
# - v1.0.0    initial version

- name: setting selinux to targeted and enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: starting and enableing firewalld
  service:
    name: firewalld
    enabled: true
    state: started

- name: setting dns servers to labipa
  shell: 'nmcli con mod "System eth1" ipv4.dns 172.16.20.2 +ipv4.dns 8.8.8.8'

- name: add PEERDNS=no to System eth0
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "PEERDNS=no"
    state: present
  notify:
    - reload network
    - restart network
